pre-release-replacements = [
	# Update the CHANGELOG
	{ file = "../CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
	{ file = "../CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
	{ file = "../CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}" },
	{ file = "../CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly = 1 },
	{ file = "../CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/dart-sys/dart-sys/compare/{{tag_name}}...HEAD", exactly = 1 },

	# Update the `dart-sys = "x.x.x"` line in the README
	{ file = "../README.md", search = "dart-sys = \"[0-9]+\\.[0-9]+\\.[0-9]+\"", replace = "dart-sys = \"{{version}}\"" },

	# Update the `version = "x.x.x"` line in the `Cargo.toml`
	{ file = "../tests/Cargo.toml", search = "version = \"[0-9]+\\.[0-9]+\\.[0-9]+\"", replace = "version = \"{{version}}\"" },

]
tag-prefix = ""
allow-branch = ["main"]
tag-message = "GitHub Actions"
pre-release-commit-message = "(chore): release v{{version}}"
