[workspace]
members = ["ffi", "examples/**/*"]

[workspace.package]
version = "2.0.1"
edition = "2021"
license = "MIT"
description = "Bindings to the dart native extensions api"
repository = "https://github.com/dart-sys/dart-sys"
keywords = [
	"dart",
	"native",
	"extension",
	"extensions",
	"dart-sys",
	"ffi",
	"flutter",
	"no-std",
	"code-generation",
	"bindings",
]
categories = ["no-std", "development-tools::ffi", "external-ffi-bindings"]


[workspace.dependencies]
dart-sys = { path = "ffi" }

[profile.release]
strip = "debuginfo"
lto = "thin"
