name: hello_world
version: 0.0.0
description: Example dart application that uses Dart-sys to call a "Hello World!" Rust function from Dart.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  test_utils:
    path: ../test_utils
