[package]
name = "structs"
version = "0.0.0"

[dependencies]
rand = { workspace = true }
libc = { workspace = true }
lazy_static = { workspace = true }
dart-sys-fork = { workspace = true }

[lib]
crate-type = ["cdylib"]
