name: structs
version: 0.0.0
description: Example dart application that uses Dart-sys to generate a random number from Rust.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
