[package]
name = "dart-sys"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
build = "build.rs"
readme = "../README.md"


[build-dependencies]
bindgen = { version = "0.63.0" }
chrono = { version = "0.4.23" }
reqwest = { version = "0.11.13", features = ["blocking"] }
sha2 = { version = "0.10.6" }
zip = { version = "0.6.3" }

[features]
# std = []
default = []
docs_only = []
download_dart_sdk_stable = ["download_dart_sdk"]
download_dart_sdk_dev = ["download_dart_sdk"]
download_dart_sdk_beta = ["download_dart_sdk"]
download_dart_sdk = []
ci = []


[package.metadata.docs.rs]
features = ["docs_only"]


# [[example]]
# name = "async"
# crate-type = ["cdylib"]

# [[example]]
# name = "sync"
# crate-type = ["cdylib"]
