name: CD

on:
  release:
    types: [published]
  workflow_run:
    workflows: [CI]
    types: [completed]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: debug

jobs:
  # Run if CI workflow was successful
  ci-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout sources
      - name: Checkout Sources
        uses: actions/checkout@v2

      # Install rust toolchain
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      # Install cargo-release
      - name: Install cargo-release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-release

      # If not on main, exit workflow without error
      - name: Exit workflow if not on main
        if: ${{ github.ref != 'refs/heads/main' }}
        run: exit 0

      # Run cargo release
      - name: Run cargo release
        uses: actions-rs/cargo@v1
        with:
          command: release
          args: patch --no-confirm --execute --config .github/cargo-release.toml

  # Run if CI workflow was NOT successful
  ci-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Exit workflow without error
        run: exit 0
