name: Examples tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: debug

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout sources
      - name: Checkout Sources
        uses: actions/checkout@v2

      # Cache cargo, rust, and dart
      - name: Cache cargo, rust, and dart
        id: cache-release
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/target/
            ~/.pub-cache/
          key: ${{ runner.os }}-cargo-release

      # Install Rust toolchain
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        if: steps.cache-release.outputs.cache-hit != 'true'
        with:
          override: true
          toolchain: stable

      # Install dart
      - name: Install dart
        if: steps.cache-release.outputs.cache-hit != 'true'
        uses: dart-lang/setup-dart@v1

      # Run dart tests for all examples in `/examples`
      - name: Run dart tests for all examples in `/examples`
        run: |
          cd examples
          for dir in */; do
            cd $dir
            dart pub get
            dart test
            cd ..
          done
